### ISSUE TITLE
Unable to use with postcss-cli

### ISSUE THREAD

**Issue by remino** [csstools/postcss-sass#34]
Is it possible to use this as a parser with [postcss-cli](https://github.com/postcss/postcss-cli)?

I tried with the following:

```sass
// main.sass
body
	text-shadow: 0 0 0.5rem black
```

```js
// postcss.config.js
// (`"type": "module"` in `package.json`)
export default (ctx) => ({
  map: ctx.options.map,
  parser: ctx.file.extname === '.sass' ? '@csstools/postcss-sass' : false,
  plugins: {
    cssnano: ctx.env === 'production' ? {} : false,
  },
})
```

```sh
# Shell command
npx postcss main.sass
```

But I get this error:

```
TypeError: Cannot read properties of undefined (reading 'length')
    at MapGenerator.clearAnnotation ([redacted]/postcsstrial/node_modules/postcss/lib/map-generator.js:81:36)
    at MapGenerator.generate ([redacted]/postcsstrial/node_modules/postcss/lib/map-generator.js:325:10)
    at LazyResult.stringify ([redacted]/postcsstrial/node_modules/postcss/lib/lazy-result.js:277:20)
    at LazyResult.runAsync ([redacted]/postcsstrial/node_modules/postcss/lib/lazy-result.js:443:17)
    at LazyResult.async ([redacted]/postcsstrial/node_modules/postcss/lib/lazy-result.js:221:30)
    at LazyResult.then ([redacted]/postcsstrial/node_modules/postcss/lib/lazy-result.js:206:17)
    at file://[redacted]/postcsstrial/node_modules/postcss-cli/index.js:255:10
    at async Promise.all (index 0)
```

**Comment by remino** [comment]
I also tried with the following config, and I got a different error message:

```js
// postcss.config.js
export default (ctx) => ({
	map: ctx.options.map,
	plugins: {
		'@csstools/postcss-sass': {},
		cssnano: ctx.env === 'production' ? {} : false,
	},
})
```

```
CssSyntaxError: [redacted]/postcsstrial/main.sass:2:2: Unknown word
You tried to parse Sass with the standard CSS parser; try again with the postcss-sass parser

  1 | body
> 2 | 	text-shadow: 0 0 0.5rem black
    | 	^
  3 |
  4 |
```

**Comment by remino** [comment]
I think I figured out a workaround. I actually removed the module and just piped the `sass` output to `postcss`:

```js
// postcss.config.js
export default (ctx) => ({
	map: ctx.options.map,
	plugins: {
		autoprefixer: {},
		cssnano: {},
	},
})
```

```sh
sass main.sass | npx postcss
```

```
/* CSS output */
body{text-shadow:0 0 .5rem #000}
/*# sourceMappingURL=data:application/json;base64,[redacted] */
```

This will have to do for now.

**Comment by romainmenke** [comment]
This is well documented : https://github.com/csstools/postcss-sass#postcss

> The standard CSS parser included with PostCSS may not be able to parse SCSS specific features like inline comments. To accurately parse SCSS, use the [SCSS Parser](https://github.com/postcss/postcss-scss).

**Comment by remino** [comment]
> To accurately parse SCSS

Since my original post, I’ve been talking about Sass, the indented syntax, and not SCSS. Why do you keep thinking that I’m talking about making SCSS work?
