### ISSUE TITLE
Failing on node 18

### ISSUE THREAD

**Issue by nwhittaker** [csstools/postcss-sass#35]
Node 18 broke the way the `source-map` dependency was detecting the node environement[^1]. Likely just need to bump `source-map` to `0.7.4` to get the fix[^2].

[^1]: https://github.com/mozilla/source-map/issues/460
[^2]: https://github.com/mozilla/source-map/pull/350

<details>
<summary>Error report</summary>

```
=================================================================================

ENV Summary:

  TIME: Thu Jan 19 2023 10:54:17 GMT-0500 (Eastern Standard Time)
  TITLE: ember
  ARGV:
  - ~/.nvm/versions/node/v18.12.1/bin/node
  - ~/my-project/node_modules/.bin/ember
  - build
  - --environment=production
  EXEC_PATH: ~/.nvm/versions/node/v18.12.1/bin/node
  TMPDIR: /var/folders/8_/8dr731q50v71lqh6m55cyfcr0000gp/T
  SHELL: /bin/zsh
  PATH:
  - /var/folders/8_/8dr731q50v71lqh6m55cyfcr0000gp/T/yarn--1674143639272-0.8902524960293507
  - ~/my-project/node_modules/.bin
  - ~/.config/yarn/link/node_modules/.bin
  - ~/.nvm/versions/node/v18.12.1/libexec/lib/node_modules/npm/bin/node-gyp-bin
  - ~/.nvm/versions/node/v18.12.1/lib/node_modules/npm/bin/node-gyp-bin
  - ~/.nvm/versions/node/v18.12.1/bin/node_modules/npm/bin/node-gyp-bin
  - ~/.nvm/versions/node/v18.12.1/bin
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  - ~/.nvm/versions/node/v18.12.1/bin
  PLATFORM: darwin x64
  FREEMEM: 4703944704
  TOTALMEM: 77309411328
  UPTIME: 1376163
  LOADAVG: 8.81982421875,5.58447265625,3.79443359375
  CPUS:
  - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz - 3800
  - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz - 3800
  - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz - 3800
  - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz - 3800
  - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz - 3800
  - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz - 3800
  - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz - 3800
  - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz - 3800
  - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz - 3800
  - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz - 3800
  - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz - 3800
  - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz - 3800
  - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz - 3800
  - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz - 3800
  - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz - 3800
  - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz - 3800
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.18.1
  - brotli: 1.0.9
  - cldr: 41.0
  - icu: 71.1
  - llhttp: 6.0.10
  - modules: 108
  - napi: 8
  - nghttp2: 1.47.0
  - nghttp3: 0.7.0
  - ngtcp2: 0.8.1
  - node: 18.12.1
  - openssl: 3.0.7+quic
  - tz: 2022b
  - unicode: 14.0
  - uv: 1.43.0
  - v8: 10.2.154.15-node.12
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: Error: You must provide the URL of lib/mappings.wasm by calling SourceMapConsumer.initialize({ 'lib/mappings.wasm': ... }) before using SourceMapConsumer
    at readWasm (~/my-project/node_modules/@csstools/postcss-sass/node_modules/source-map/lib/read-wasm.js:8:13)
    at wasm (~/my-project/node_modules/@csstools/postcss-sass/node_modules/source-map/lib/wasm.js:25:16)
    at ~/my-project/node_modules/@csstools/postcss-sass/node_modules/source-map/lib/source-map-consumer.js:264:14
    at async Promise.all (index 0)
  - code: [undefined]
  - codeFrame: You must provide the URL of lib/mappings.wasm by calling SourceMapConsumer.initialize({ 'lib/mappings.wasm': ... }) before using SourceMapConsumer
  - errorMessage: You must provide the URL of lib/mappings.wasm by calling SourceMapConsumer.initialize({ 'lib/mappings.wasm': ... }) before using SourceMapConsumer
        at PostcssCompiler
-~- created here: -~-
    at PostcssCompiler.Plugin (~/my-project/node_modules/broccoli-plugin/index.js:7:31)
    at new CachingWriter (~/my-project/node_modules/broccoli-caching-writer/index.js:18:10)
    at new PostcssCompiler (~/my-project/node_modules/broccoli-postcss-single/index.js:20:5)
    at ~/my-project/node_modules/ember-cli-postcss/index.js:34:12
    at Array.map (<anonymous>)
    at PostcssPlugin.toTree (~/my-project/node_modules/ember-cli-postcss/index.js:31:36)
    at ~/my-project/node_modules/ember-cli-preprocess-registry/preprocessors.js:188:26
    at Array.forEach (<anonymous>)
    at processPlugins (~/my-project/node_modules/ember-cli-preprocess-registry/preprocessors.js:186:11)
    at module.exports.preprocessCss (~/my-project/node_modules/ember-cli-preprocess-registry/preprocessors.js:156:10)
-~- (end) -~-
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: You must provide the URL of lib/mappings.wasm by calling SourceMapConsumer.initialize({ 'lib/mappings.wasm': ... }) before using SourceMapConsumer
        at PostcssCompiler
-~- created here: -~-
    at PostcssCompiler.Plugin (~/my-project/node_modules/broccoli-plugin/index.js:7:31)
    at new CachingWriter (~/my-project/node_modules/broccoli-caching-writer/index.js:18:10)
    at new PostcssCompiler (~/my-project/node_modules/broccoli-postcss-single/index.js:20:5)
    at ~/my-project/node_modules/ember-cli-postcss/index.js:34:12
    at Array.map (<anonymous>)
    at PostcssPlugin.toTree (~/my-project/node_modules/ember-cli-postcss/index.js:31:36)
    at ~/my-project/node_modules/ember-cli-preprocess-registry/preprocessors.js:188:26
    at Array.forEach (<anonymous>)
    at processPlugins (~/my-project/node_modules/ember-cli-preprocess-registry/preprocessors.js:186:11)
    at module.exports.preprocessCss (~/my-project/node_modules/ember-cli-preprocess-registry/preprocessors.js:156:10)
-~- (end) -~-
  - name: Error
  - nodeAnnotation: [undefined]
  - nodeName: PostcssCompiler
  - originalErrorMessage: You must provide the URL of lib/mappings.wasm by calling SourceMapConsumer.initialize({ 'lib/mappings.wasm': ... }) before using SourceMapConsumer
  - stack: Error: You must provide the URL of lib/mappings.wasm by calling SourceMapConsumer.initialize({ 'lib/mappings.wasm': ... }) before using SourceMapConsumer
    at readWasm (~/my-project/node_modules/@csstools/postcss-sass/node_modules/source-map/lib/read-wasm.js:8:13)
    at wasm (~/my-project/node_modules/@csstools/postcss-sass/node_modules/source-map/lib/wasm.js:25:16)
    at ~/my-project/node_modules/@csstools/postcss-sass/node_modules/source-map/lib/source-map-consumer.js:264:14
    at async Promise.all (index 0)

=================================================================================
```
<details>

**Comment by romainmenke** [comment]
This has been published as `5.1.0`.

Thank you for reporting
